### ISSUE TITLE
Missing Phoenix boss cards

### ISSUE THREAD

**Issue by DarkBitz** [BlueMystical/Rappelz_BeltCalculator#1]

**Comment by BlueMystical** [comment]
hi there,
I had not played the game is a while.
Would you mind to pass me the info of those cards so i can add them ?
If you have Images of them would be great.
Thank you.

**Comment by DarkBitz** [comment]
[Boss Card] Chaotic Phoenix: Warrior

Strength / Dexterity: +10%
Critical Power: +30%
Gain Chaotic Phoenix: Warrior effect: P. Atk. +50%, Atk. Spd +30%, Max HP: +20%
Chance to absorb 1% of damage to HP with attacks
Stop HP Regen

[Boss Card] Chaotic Phoenix: Magician

Intelligence / Wisdom: +10%
Critical Power: +30%
Gain Chaotic Phoenix: Magician effect: M. Atk. +50%, Cast Spd. +70%, MP Regen +25%
20% Mana reduction from spells
Stop HP Regen 

[Boss Card] Chaotic Phoenix: Summoner

Strength / Vitality / Intelligence: +5%
Critical Power: +20%
+5 Creature Mastery
+3 Creature HP/MP Expansion

**Comment by BlueMystical** [comment]
Added the new boss cards
Shame they wont have Images.
Thank you

![image](https://github.com/user-attachments/assets/dfba1c9f-96bc-49b2-a46d-49bc64778d07)
